<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <EnableNETAnalyzers>false</EnableNETAnalyzers>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../src_of_fivepd_plugin/CalloutEntityCollector.cs" Link="CalloutEntityCollector.cs" />
  </ItemGroup>
</Project>
