<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net452</TargetFramework>
    <AssemblyName>SonoranPlugin.net</AssemblyName>
    <Version>2.1.1</Version>
    <LangVersion>7.3</LangVersion>
    <Deterministic>true</Deterministic>
    <PathMap>$(MSBuildProjectDirectory)=/_/src</PathMap>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <AutomaticallyUseReferenceAssemblyPackages>false</AutomaticallyUseReferenceAssemblyPackages>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FivePD.net" Version="1.3.0" />
    <PackageReference Include="CitizenFX.Core.Client" Version="1.0.3324" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net452" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>
</Project>
